import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import { Middleware } from "openapi-fetch";
import type { paths } from "@/lib/api/lastest"; // generated by openapi-typescript
import { useAuth } from "./hooks/useAuth";

export function useApi() {
  const fetchClient = createFetchClient<paths>({
    baseUrl: import.meta.env.VITE_API_URL,
  });
  const $api = createClient(fetchClient);
  const { user } = useAuth()!
  if (user) {
    const accessToken = user.jwtToken
    const authMiddleware: Middleware = {
      async onRequest({ request }) {
        request.headers.set("Authorization", `Bearer ${accessToken}`);
        return request;
      },
    };
    fetchClient.use(authMiddleware);
  }

  return $api;
} 