FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source/src
COPY src/bikamp/bikamp.csproj bikamp/
COPY src/test/test.csproj test/
WORKDIR /source/src/test
#RUN --mount=type=cache,target=/root/.nuget/packages \
RUN dotnet restore
COPY . /source
RUN dotnet build "test.csproj" -c Release -o /build 
COPY /docker/test/appsettings.json /build/appsettings.json

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base

FROM base AS final
ENV APP_SETTINGS_JSON_PATH="./appsettings.json"
COPY --from=build /build .
ENTRYPOINT ["dotnet", "test", "test.dll","-v","n"]
