services:
  api: 
    container_name: "bikamp_api"
    image: api 
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    profiles: ["server"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5259:5259
    volumes:
      - ./docker/api/appsettings.json:/app/appsettings.json
    healthcheck:
      test: curl --fail http://localhost:5259/healthz || exit
      start_period: 5s
      interval: 30s
      timeout: 30s
      retries: 3

  db:
    container_name: "bikamp_bd"
    image: mysql
    profiles: ["server", "test", "db"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bikamp    
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    volumes: 
      - bikamp-mysql-volume:/var/lib/mysql
      - ./db/startup.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/base.sql:/docker-entrypoint-initdb.d/2.sql
      - ./db/populate.sql:/docker-entrypoint-initdb.d/3.sql
    ports:
      - 42333:3306
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e "select 'funcionando'" $$MYSQL_DATABASE
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  test: 
    container_name: "bikamp_test"
    image: test 
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    profiles: ["test"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5259:5259
  whodb:
    image: clidey/whodb
    environment:
      WHODB_MYSQL: '[{"host":"db","user":"api","password":"api","database":"mysql"}]' 
    ports:
      - "8080:8080"

volumes:
  bikamp-mysql-volume:
